export { default as sidebarInterview } from './interview'
export { default as sidebarAlgorithm } from './algorithm'
export { default as sidebarPatterns } from './patterns'

export { sidebarDesign } from './vue-source'
export { sidebarArticle } from './article'
export * from './frontend'
export { sidebarDevelops, sidebarTools } from './develops'
export { sidebarGo, sidebarSql, sidebarReg, sidebarOtherBe } from './backend'
export { sidebarTypescript } from './typescript'
